<!DOCTYPE html>
<html lang="en">
<head>
<title>HTML headセクション解析</title>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<link rel="stylesheet/less" href="/static/common/less/bootstrap.less" />
<script src="/static/common/js/less-1.1.3.min.js"></script>


<style type="text/css">
body {
    padding : 60px;

}
</style>

</head>
<body>
    <div class="topbar">
      <div class="topbar-inner">
        <div class="container-fluid">
          <a class="brand" href="/">HTML headセクション解析</a>
          <p class="pull-right" id="container-profile-status"><a onClick="return popup(this);"  href="/auth/connect">ログイン</a></p>
        </div>
      </div>
    </div>
